### ISSUE TITLE
Fisheye Tutorial

### ISSUE THREAD

**Issue by herleeyandi** [scikit-image/skimage-demos#6]
Hello @stefanv I want to ask about the fish eye demo, what is the meaning of this line?
`r = 0.8 * np.exp(r**(1/2.1) / 1.8)`
what is the 2.1 and 1.8?, is that value of camera focal which is `(fx,fy)`?, and which equation did you use to transform to fish eye based on [this](https://wiki.panotools.org/Fisheye_Projection)

**Comment by stefanv** [comment]
I just made up that formula, and played with the values a bit.  I'm sorry not to have a more satisfactory explanation!  But what you're looking at is a re-mapping of the radius coordinate, after we've converted from (x, y) to (r, phi).

You should probably implement the transformation in the link you posted instead.  Let me know how that works out!
